import java.util.Random;
import java.util.Scanner;

public class Zadanie {

        public static void main(String[] args) {

            int x;
            int y;

            Scanner scanner = new Scanner(System.in);
            System.out.println("Enter x: ");
            x = scanner.nextInt();
            Random random = new Random();
            y = random.nextInt(2);
            System.out.println("Y generated by system: " + y );
            System.out.println("x == y " + (x == y) );

        }
    }

