import java.util.Random;
import java.util.Scanner;

public class Zadanie2 {

    public static void main(String[] args) {

        int x;
        int y;

        Scanner scanner = new Scanner(System.in);
        System.out.println("Enter x: ");
        x = scanner.nextInt();
        Random random = new Random();
        int max = 6;
        int min = 1;
        y = random.nextInt((max - min) + 1) + min;
        System.out.println("Y generated by system: " + y);
        System.out.println("x == y " + (x == y));

    }


}


